# Importing Libraries 

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Loading the dataset

In [2]:
df= pd.read_csv('C:\\Users\\ADMIN\\Documents\\csv Files\\tmdb_5000_movies.csv')
df.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

# Exploratory Data Analysis and Data Cleaning

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [4]:
df= df[['id','original_title','genres','overview','keywords','production_companies','vote_average']]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    4803 non-null   int64  
 1   original_title        4803 non-null   object 
 2   genres                4803 non-null   object 
 3   overview              4800 non-null   object 
 4   keywords              4803 non-null   object 
 5   production_companies  4803 non-null   object 
 6   vote_average          4803 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 262.8+ KB


In [6]:
df.isnull().sum()

id                      0
original_title          0
genres                  0
overview                3
keywords                0
production_companies    0
vote_average            0
dtype: int64

In [7]:
df.dropna(inplace= True)

In [8]:
df.isnull().sum()

id                      0
original_title          0
genres                  0
overview                0
keywords                0
production_companies    0
vote_average            0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
import ast

In [12]:
def converter(obj):
    L= []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [13]:
df['genres']= df['genres'].apply(converter)
df['keywords']= df['keywords'].apply(converter)
df['production_companies']= df['production_companies'].apply(converter)

In [14]:
df.head()

id                            original_title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                production_companies  vote_average  
0  [Ingenious Film Partners, Twentieth Century Fo...           7.2  
1  [Walt Disney Pictures, Jerry Bruckheimer Films...           6.9  
2                   [Columbia Pictures, Danjaq, B24]           6.3  
3  [Legendary Pictures, Warner Bros., DC Entertai...           7.6  
4                             [Walt Disney Pictures]           6.1

In [15]:
df['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [16]:
df['overview']= df['overview'].apply(lambda x: x.split())

In [17]:
df['genres']= df['genres'].apply(lambda x: [i.replace(" ","") for i in x])

In [18]:
df['keywords']= df['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
df['production_companies']= df['production_companies'].apply(lambda x: [i.replace(" ","") for i in x])

In [19]:
df['tags']= df['genres']+df['overview']+df['keywords']+df['production_companies']

In [20]:
new_df= df[['id','original_title','tags']]

In [21]:
new_df.head()

id                            original_title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                                tags  
0  [Action, Adventure, Fantasy, ScienceFiction, I...  
1  [Adventure, Fantasy, Action, Captain, Barbossa...  
2  [Action, Adventure, Crime, A, cryptic, message...  
3  [Action, Crime, Drama, Thriller, Following, th...  
4  [Action, Adventure, ScienceFiction, John, Cart...

In [22]:
new_df['tags']= new_df['tags'].apply(lambda x: ' '.join(x))

In [23]:
new_df.head()

id                            original_title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                                tags  
0  Action Adventure Fantasy ScienceFiction In the...  
1  Adventure Fantasy Action Captain Barbossa, lon...  
2  Action Adventure Crime A cryptic message from ...  
3  Action Crime Drama Thriller Following the deat...  
4  Action Adventure ScienceFiction John Carter is...

In [24]:
new_df['tags'][0]

'Action Adventure Fantasy ScienceFiction In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d IngeniousFilmPartners TwentiethCenturyFoxFilmCorporation DuneEntertainment LightstormEntertainment'

In [25]:
new_df['tags']= new_df['tags'].apply(lambda x: x.lower())

In [26]:
new_df['tags'][0]

'action adventure fantasy sciencefiction in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d ingeniousfilmpartners twentiethcenturyfoxfilmcorporation duneentertainment lightstormentertainment'

# Applying Recommendation Algorithms

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features= 5000, stop_words= 'english')

In [28]:
cv.fit_transform(new_df['tags']).toarray().shape

(4800, 5000)

In [29]:
vectors= cv.fit_transform(new_df['tags']).toarray()

In [30]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
import nltk

In [32]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [33]:
def stem(text):
    y= []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [34]:
new_df['tags']= new_df['tags'].apply(stem)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
cosine_similarity(vectors)

array([[1.        , 0.08885233, 0.05827165, ..., 0.02391824, 0.02597622,
        0.        ],
       [0.08885233, 1.        , 0.06558258, ..., 0.0269191 , 0.        ,
        0.        ],
       [0.05827165, 0.06558258, 1.        , ..., 0.02648136, 0.        ,
        0.        ],
       ...,
       [0.02391824, 0.0269191 , 0.02648136, ..., 1.        , 0.07082882,
        0.04847862],
       [0.02597622, 0.        , 0.        , ..., 0.07082882, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04847862, 0.05264981,
        1.        ]])

In [37]:
cosine_similarity(vectors).shape

(4800, 4800)

In [38]:
similarity= cosine_similarity(vectors)

In [39]:
similarity[0]

array([1.        , 0.08885233, 0.05827165, ..., 0.02391824, 0.02597622,
       0.        ])

In [40]:
similarity[0].shape

(4800,)

In [41]:
sorted(list(enumerate(similarity[0])), reverse= True, key= lambda x:x[1])[1:6]

[(539, 0.28676966733820214),
 (1213, 0.26629706611944254),
 (507, 0.2649064714130088),
 (61, 0.24779731389167606),
 (1201, 0.24738534799764675)]

In [42]:
def recommend(movie):
    movie_index= new_df[new_df['original_title']==movie].index[0]
    distances= similarity[movie_index]
    movie_list= sorted(list(enumerate(distances)), reverse= True, key= lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].original_title)

In [43]:
recommend('Avatar')

Titan A.E.
Aliens vs Predator: Requiem
Independence Day
Jupiter Ascending
Predators


In [44]:
recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
Ant-Man
Captain America: Civil War


In [45]:
recommend('Man of Steel')

Superman Returns
Superman II
Batman v Superman: Dawn of Justice
Superman
Superman IV: The Quest for Peace
